#!/bin/bash
#
#  Command Line Interface to start all services associated with the Getting-Started Tutorial
#
#  For this tutorial the commands are merely a convenience script to run docker-compose
#

set -e

if (( $# != 1 )); then
    echo "Illegal number of parameters"
    echo "usage: services [start|stop]"
    exit 1
fi

command="$1"
case "${command}" in
	"help")
        echo "usage: services [start|stop]"
        ;;
    "start")
		echo "Starting containers"
		docker-compose -p fiware up -d
		sleep 2
		echo "Loading context data"
		./import-data
		echo "Provisioning IoT devices"
		./provision-devices
		;;
	"stop")
		echo "Stopping containers"
		docker-compose -p fiware down
		echo "Removing volumes"
		docker volume prune --force
		;;
	"create")
		echo "Obtaining Mongo DB image"
		docker pull mongo:3.6
		echo "Obtaining Latest Orion Image"
		docker pull fiware/orion
		echo "Obtaining Latest UltraLight IoT Agent"
		docker pull fiware/iotagent-ul
		echo "Recreate Context-Providers proxy"
		docker build -t fiware/cp-web-app ./proxy
		;;
esac