version: "3"
services:
  context-db:
    image: mongo:3.6
    hostname: context-db
    container_name: db-mongo
    ports:
        - "27017:27017"
    networks:
        - default
    command: --bind_ip_all --smallfiles

  historic-db-mysql:
      restart: always
      image: mysql:5.7
      hostname: historic-db-mysql
      container_name: db-mysql
      expose:
        - "3306"
      ports:
        - "3306:3306"
      networks:
        - default
      environment:
        - "MYSQL_ROOT_PASSWORD=123"
        - "MYSQL_ROOT_HOST=%"

  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - context-db
      - context-provider
    networks:
        - default
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost context-db -logLevel DEBUG


  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: fiware-cygnus
    networks:
        - default
    depends_on:
        - historic-db-mysql
    expose:
        - "5080"
    ports:
        - "5080:5080"
    environment:
        - "CYGNUS_MYSQL_HOST=historic-db-mysql"
        - "CYGNUS_MYSQL_PORT=3306"
        - "CYGNUS_MYSQL_USER=root" 
        - "CYGNUS_MYSQL_PASS=123" 
        - "CYGNUS_LOG_LEVEL=DEBUG"
        - "CYGNUS_SERVICE_PORT=5050"
        - "CYGNUS_API_PORT=5080"

  iot-agent:
    image: fiware/iotagent-ul:latest
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - context-db
      - orion
    networks:
        - default
    ports:
        - "4041:4041"
        - "7896:7896"
    environment:
        - "IOTA_CB_HOST=orion" # name of the context broker to update context
        - "IOTA_CB_PORT=1026" # port the context broker listens on to update context
        - "IOTA_NORTH_PORT=4041"
        - "IOTA_REGISTRY_TYPE=mongodb" #Whether to hold IoT device info in memory or in a database
        - "IOTA_LOG_LEVEL=DEBUG" #The log level of the IoT Agent
        - "IOTA_TIMESTAMP=true"
        - "IOTA_MONGO_HOST=context-db" # The host name of ongoDB
        - "IOTA_MONGO_PORT=27017" # The port mongoDB is listening on
        - "IOTA_MONGO_DB=iotagentul" # The name of the database used in mongoDB
        - "IOTA_HTTP_PORT=7896" # The port used for device traffic over HTTP
        - "IOTA_PROVIDER_URL=http://iot-agent:4041"

  context-provider:
    image: fiware/cp-web-app:latest
    hostname: context-provider
    container_name: context-provider
    networks:
        - default
    expose:
        - "3000"
        - "3001"
    ports:
        - "3000:3000"
        - "3001:3001"
    environment:
        - "DEBUG=proxy:*"
        - "PORT=3000" # Port used by the content provider proxy and web-app for viewing data
        - "IOTA_HTTP_HOST=iot-agent"
        - "IOTA_HTTP_PORT=7896"
        - "DUMMY_DEVICES_PORT=3001" # Port used by the dummy IOT devices to receive commands
        - "DUMMY_DEVICES_API_KEY=4jggokgpepnvsb2uv4s40d59ov"
        - "CONTEXT_BROKER=http://orion:1026/v2" # URL of the context broker to update context
        - "WUNDERGROUND_KEY_ID=<ADD_YOUR_KEY_ID>"
        - "TWITTER_CONSUMER_KEY=<ADD_YOUR_CONSUMER_KEY>"
        - "TWITTER_CONSUMER_SECRET=<ADD_YOUR_CONSUMER_SECRET>"

networks:
  default: