version: "3.8"

services:


  # Cygnus is configured to write context data to Mongo-DB
  cygnus:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/cygnus-ngsi:${CYGNUS_VERSION}
    hostname: cygnus
    container_name: fiware-cygnus
    networks:
      - default
    expose:
      - "${CYGNUS_SERVICE_PORT}"
      - "${CYGNUS_API_PORT}"
    ports:
      - "${CYGNUS_SERVICE_PORT}:${CYGNUS_SERVICE_PORT}" # localhost:5050
      - "${CYGNUS_API_PORT}:${CYGNUS_API_PORT}" # localhost:5080
    environment:
      - "CYGNUS_CKAN_HOST=ckan"
      - "CYGNUS_CKAN_PORT=5000"
      - "CYGNUS_CKAN_SKIP_CONF_GENERATION=true"
      - "CYGNUS_CKAN_ENABLE_ENCODING=false"
      - "CYGNUS_CKAN_ENABLE_GROUPING=false"
      - "CYGNUS_CKAN_ENABLE_NAME_MAPPINGS=false"
      - "CYGNUS_CKAN_SKIP_NAME_MAPPINGS_GENERATION=false"
      - "CYGNUS_CKAN_ENABLE_LOWERCASE=false"
      - "CYGNUS_CKAN_DATA_MODEL=dm-by-entity"
      - "CYGNUS_CKAN_ATTR_PERSISTANCE=row"
      - "CYGNUS_CKAN_ORION_URL=http://orion:${ORION_PORT}"
      - "CYGNUS_CKAN_API_KEY=29f1bec9-0fa2-4aaf-a1fc-6a7ecb233d61"
      - "CYGNUS_LOG_LEVEL=DEBUG" # The logging level for Cygnus
      - "CYGNUS_SERVICE_PORT=${CYGNUS_SERVICE_PORT}" # Notification Port that Cygnus listens when subcribing to context data changes
      - "CYGNUS_API_PORT=${CYGNUS_API_PORT}" # Port that Cygnus listens on for operational reasons
    healthcheck:
      test: curl --fail -s http://localhost:${CYGNUS_API_PORT}/v1/version || exit 1
 